# Generated by Django 2.2 on 2021-01-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='accounts.Relationship', to='accounts.Profile'),
        ),
    ]
