# Generated by Django 2.2 on 2021-01-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        ('accounts', '0005_profile_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.ManyToManyField(related_name='profiles', through='webapp.Messages', to='accounts.Profile', verbose_name='сообщение'),
        ),
    ]
